const ListsCreated = {"Countries" : [
  "Australia.png",
  "Austria.jpg",
  "Brazil 1.jpg",
  "Brazil 2.jpg",
  "Brazil 60s.png",
  "Brazil 70s.png",
  "Brazil 80s.png",
  "Brazil AvantGarde.jpg",
  "Brazil Pyschedelia.png",
  "Brazil Rock.png",
  "Brazil Soul.png",
  "Britpop2.png",
  "Canada.jpg",
  "Chile.jpg",
  "France.jpg",
  "Iceland.jpg",
  "Japan 1.png",
  "Japan 2.png",
  "Japan 3.jpg",
  "Japan 80s.jpg",
  "Japan Folk.jpg",
  "Mexico.jpg",
  "Northern Ireland.png",
  "Peru.jpg",
  "Poland Essentials.jpg",
  "Poland Synthpop.jpg",
  "Portugal.jpg",
  "Scotland.png",
  "UK Hiphop.jpg",
  "United States.jpg"
],
"Genres" : [
  "Acid-Funk-Jazz.jpeg",
  "Afrobeat.jpg",
  "AGGROTECH.png",
  "Alt-Grunge_1990s.jpg",
  "Ambient_1.jpeg",
  "Ambient_2.png",
  "Ambient_2000s.jpg",
  "Ambient_3.jpg",
  "Ambient_DARK.jpg",
  "Ambient_DARK_2.png",
  "Art Pop_1.jpg",
  "Art Pop_2.jpg",
  "Atmospheric Sludge Metal.png",
  "Avant Garde Metal.jpg",
  "Baroque.png",
  "Bigbeat_Breakbeat.jpg",
  "Black Metal_1.jpg",
  "Black Metal_2.jpg",
  "Black Metal_Atmospheric.png",
  "Black Metal_by Country.jpg",
  "Black Metal_Hipster.png",
  "Blues.jpg",
  "Bossa 1.jpg",
  "Bossa 2.jpg",
  "Breakbeats.jpg",
  "Breakbeat_Hardcore.jpg",
  "Breakcore.jpg",
  "Breaks.jpg",
  "Britpop.jpg",
  "Britpop_2.jpg",
  "Brostep.png",
  "Brostep_Complextro.jpg",
  "Chillwave.jpg",
  "Chillwave_2.jpeg",
  "Chiptune.jpg",
  "Citypop.png",
  "Classical 1750-1830.png",
  "Classical_2.jpg",
  "Classical_3.png",
  "Country.jpg",
  "Crust_Grindcore_Powerviolence_Thrash.jpg",
  "Dancepunk.png",
  "Death Metal _2.jpg",
  "Death Metal_1.jpg",
  "Death Metal_SWEDISH.jpg",
  "Deathcore.png",
  "Deephouse.png",
  "Detroit Techno.jpg",
  "DJENT.jpg",
  "Doom MEtal.jpg",
  "Downtempo.png",
  "Drone.jpg",
  "DrumNbass.png",
  "Dubstep.jpeg",
  "Dubstep_2.JPG",
  "Dungeon-Synth_1.jpg",
  "Dungeon-Synth_2.png",
  "Dungeon-Synth_3.png",
  "East Coast Hip Hop.jpg",
  "Electro House.png",
  "Electro.jpg",
  "Electronic genre flowchart.jpg",
  "Electronic Genres.png",
  "Electronic Music Guide.jpg",
  "Electronic_Assorted.jpg",
  "Electronic_By Genre.jpg",
  "Electronic_essential.jpeg",
  "Eletronic - Witchhouse.png",
  "Eletronic.jpg",
  "Emo.jpg",
  "Emo_2.jpg",
  "Emo_Screamo.png",
  "Esencjonalna_polska_nowa_fala.jpg",
  "Experimental Hip Hop.png",
  "Experimental Hip Hop_2.jpg",
  "Experimental_Hip_Hop_3.jpg",
  "Field Recordins.png",
  "Folk Metal.png",
  "Folk Punk.jpg",
  "Folk.jpg",
  "Freak Folk.jpg",
  "Freak Folk_2.png",
  "French Electro-House.jpg",
  "Funk.jpg",
  "Funk_Modern.jpg",
  "Garage.png",
  "Glitch-Hop.jpg",
  "Glitch.png",
  "Glitch_2.jpg",
  "GOA Trance.jpg",
  "Goth.jpg",
  "Grunge.jpg",
  "Hard_Rock.jpg",
  "Harsh_noise.jpg",
  "Hip Hop_1.5.jpg",
  "Hip Hop_1.jpg",
  "Hip Hop_2.jpg",
  "Hip Hop_2010_1.png",
  "Hip Hop_2010_2.jpg",
  "Hip Hop_BAY AREA.jpg",
  "Hip Hop_Concept.jpg",
  "Hip Hop_INSTRUMENTAL.png",
  "House.jpg",
  "Indie Pop.jpg",
  "Industrial Grunge.jpg",
  "Industrial Metal.png",
  "Industrial.jpg",
  "Italo Disco.png",
  "Jangle Pop.jpg",
  "Jazz_1.jpg",
  "Jazz_2.jpg",
  "Jazz_3.jpg",
  "Jungle.jpg",
  "K Pop.jpg",
  "Krautrock_1.jpg",
  "Ladhouse.jpg",
  "Lolicore.jpg",
  "Mashup.png",
  "Math Rock.jpg",
  "Math Rock_2.jpg",
  "Mathcore.jpg",
  "Math_Rock_3.png",
  "Medieval Music 500-1400.png",
  "Metalcore.jpg",
  "Metal_100 Essentials.jpg",
  "Minimal Techno-Micro House.png",
  "Neofolk.jpg",
  "Neoprog.jpg",
  "Neurofunk.png",
  "New Wave.jpg",
  "No Wave.png",
  "Noise Rock.jpg",
  "Noise.jpg",
  "Noise_rock.jpg",
  "Nu Metal.jpg",
  "Patrician Pop.png",
  "Pop Punk.png",
  "Post Hardcore.JPG",
  "Post Hardcore_2.jpg",
  "Post Hardcore_3.jpg",
  "Post Punk, 80s Goth.jpg",
  "Post Punk.jpg",
  "Post Punk_1.jpg",
  "Post Punk_70s-80s.jpg",
  "Post Rock.jpg",
  "Post Rock_In Waves.jpg",
  "Power Metal.jpg",
  "Power Metal_2.jpg",
  "Power Metal_3.jpg",
  "Power Pop.png",
  "Prog Metal.jpg",
  "Prog Rock_2.jpg",
  "Prog Rock_3.jpg",
  "Progressive House.png",
  "Prog_MODERN.jpg",
  "Prog_MODERN_2.jpg",
  "Prog_Rock.jpeg",
  "Proto Punk.jpg",
  "Psybient_Psychill.jpg",
  "Psychedelic Drone.png",
  "Psychedelic_1960s.jpg",
  "Psychedelic_MODERN.jpg",
  "Psychobilly.jpg",
  "Punk_HARDCORE_1980s.jpg",
  "Reggae.png",
  "Reggae_2.jpg",
  "Renaissance Music.png",
  "Renaissance_2.jpg",
  "RocknRoll_1950s.jpg",
  "Rock_ALTERNATIVE.jpg",
  "Rock_DESERT.jpg",
  "Rock_PROG.png",
  "Sampling.png",
  "Scratch.jpg",
  "Screamo.jpg",
  "Shoegaze.jpeg",
  "Shoegaze2.jpg",
  "Shoegaze_1.jpg",
  "Ska.png",
  "Ska_2.png",
  "Slowcore_2.png",
  "Slowcore_Sadcore.jpg",
  "SoftRock.jpeg",
  "Soul.png",
  "Southern Hip Hop.jpg",
  "Southern Rock.jpg",
  "Spoken Word.jpg",
  "Stoner Rock.jpg",
  "Stoner Rock_2.jpg",
  "Surf Rock.gif",
  "Swing.jpg",
  "Synthpop.jpg",
  "Thrash Metal.jpg",
  "Traditional Metal.png",
  "Trance.jpg",
  "Trip Hop.jpeg",
  "Twee Pop.jpg",
  "Vaporwave.jpg",
  "Vaporwave_2.jpg",
  "Warm Drone.jpg",
  "West Coast HIp Hop.jpg",
  "Witch House.png",
  "Zeuhl.png"
],
"Internet" : [
  "4chan Board Core 1.png",
  "4chan Pol.jpg",
  "9gag Core.jpg",
  "Board Core 2.jpg",
  "Tumblr.png",
  "Twitter Core 1.png",
  "Twitter Core 2.jpg"
],
"Other" : [
  "4AD.jpeg",
  "Anime.jpg",
  "Baldcore.jpg",
  "Bawwcore.jpg",
  "Brave New World.jpg",
  "Concept-albums.png",
  "Creepy_&_Unsettling 1.jpg",
  "Creepy_&_Unsettling 2.jpg",
  "DadRockers_Guide_to_modern_music.jpg",
  "EDM_labels.png",
  "Electronic-genres.png",
  "Essential_bass+drums_power_duos.png",
  "Fallcore.png",
  "Fantano-core.png",
  "Fedora Core.jpg",
  "Feels.jpg",
  "Fierce.png",
  "Glass_breaks.jpg",
  "Happyfinal.png",
  "Hipster_Metal.jpeg",
  "Image.jpg",
  "Insane-core.png",
  "INSANECORE.png",
  "Kitten-Core.jpg",
  "Live_Albums.jpg",
  "M.jpg",
  "Memejizz.png",
  "Mu-core2012.jpg",
  "Mucorecolorcore.jpg",
  "Mucorecrabcore.jpg",
  "Mucorehappy.png",
  "Mucoreinbetweeners.jpg",
  "Mucoremusicians.png",
  "Mucoresoundtrack.jpg",
  "Mucoreswag.jpg",
  "Mucorewhitepeoplemusic.png",
  "Mulittv.jpg",
  "New to mu.jpg",
  "Overarching Story-Core.jpg",
  "Patrician_Rock.jpeg",
  "PATRISHIANCOREMAN.jpg",
  "Post-Avant JazzCore.jpg",
  "Scarufficore.png",
  "Sexcore.jpg",
  "Shitcore.png",
  "Singing Core.jpg",
  "Sub_mu_Essentials.jpg",
  "Summer Core.jpg",
  "Summercore.jpg",
  "Swnss.png",
  "Video_Game_OST.jpg",
  "Weed 1.jpeg",
  "Weed 2.jpeg",
  "Winter Core.jpg",
  "Winter Core.png",
  "Wrong_generashun.jpeg"
],
"Seasons" : [
  "Christmas.jpg",
  "Summer Core 1.jpg",
  "Summer Core 2.jpg",
  "Summer Core 3.png"
],
"Themed" : [
  "September Eleventh.jpg"
],
"Years" : [
  "1950s Rock'n'Roll.jpg",
  "1950s.png",
  "1960s Jazz.jpg",
  "1960s Psychedelia.jpg",
  "1960s.jpg",
  "1970s 1.jpg",
  "1970s 2.jpg",
  "1970s 3.jpg",
  "1970s Post-Punk.jpg",
  "1970s Punk.jpg",
  "1980s.jpg",
  "1990s 1.jpg",
  "1990s 2.jpg",
  "1990s Alternative & Grunge.jpg",
  "1990s Electronic.jpg",
  "1990s Punk.jpg",
  "2000s 1.jpg",
  "2000s 2.jpg",
  "2000s Punk.jpg",
  "2010s 1.jpg",
  "2010s 2.jpg",
  "2010s Hip Hop.jpg"
]};