const ListsCreated = {"Countries" : [
  "Australia.png",
  "Austria.jpg",
  "Belgium.png",
  "Brazil - AvantGarde.jpg",
  "Brazil - Pyschedelia.png",
  "Brazil - Rock.png",
  "Brazil - Soul.png",
  "Brazil 1.jpg",
  "Brazil 2.jpg",
  "Brazil 60s.png",
  "Brazil 70s.png",
  "Brazil 80s.png",
  "Canada.jpg",
  "Chile.jpg",
  "France.jpg",
  "Iceland.jpg",
  "Japan 1.png",
  "Japan 2.png",
  "Japan 3.jpg",
  "Japan 4.png",
  "Japan 80s.jpg",
  "Japan Folk.jpg",
  "Mexico.jpg",
  "Northern Ireland.png",
  "Peru.jpg",
  "Poland Essentials.jpg",
  "Poland Synthpop.jpg",
  "Portugal.jpg",
  "Scotland.png",
  "Spain - Rap.png",
  "UK Hiphop.jpg",
  "United States.jpg"
],
"Drugs" : [
  "Lsd Core.png",
  "Weed Core 1.jpeg",
  "Weed Core 2.jpeg"
],
"Genres" : [
  "Classical - Ancient .png",
  "Classical - Contemporary Classical.jpg",
  "Classical 1.png",
  "Classical 2.jpg",
  "Classical 3.png",
  "Classical 4.jpg",
  "Hip Hop - Bay Area.jpg",
  "Hip Hop - Concept.jpg",
  "Hip Hop - East Coast.jpg",
  "Hip Hop - Experimental 1.png",
  "Hip Hop - Experimental 2.jpg",
  "Hip Hop - Experimental 3.jpg",
  "Hip Hop - Instrumental.png",
  "Hip Hop - Noise.jpg",
  "Hip Hop - Southern.jpg",
  "Hip Hop - Triphop.jpeg",
  "HIp Hop - West Coast.jpg",
  "Hip Hop 1.jpg",
  "Hip Hop 2.jpg",
  "Hip Hop 3.jpg",
  "Hip Hop 4.jpg",
  "Jazz - Acid Funk.jpeg",
  "Jazz - Post Avan Guard.jpg",
  "Jazz 1.jpg",
  "Jazz 2.jpg",
  "Jazz 3.jpg",
  "Jazz 4.jpg",
  "Jazz 5.jpg",
  "Jazz Chamber.jpeg",
  "Jazz Guitar.png",
  "Reggae - Reggaeton.jpg",
  "Reggae 1.jpg",
  "Reggae 2.png",
  "Reggae 3.png"
],
"Internet" : [
  "4chan Board Core 1.png",
  "4chan Board Core 2.jpg",
  "4chan Pol.jpg",
  "9gag Core.jpg",
  "Fedora Core.jpg",
  "Tumblr.png",
  "Twitter Core 1.png",
  "Twitter Core 2.jpg"
],
"Other" : [
  "Bawwcore.jpg",
  "Brave New World.jpg",
  "Concept-albums.png",
  "DadRockers_Guide_to_modern_music.jpg",
  "EDM_labels.png",
  "Electronic-genres.png",
  "Essential_bass+drums_power_duos.png",
  "Fantano-core.png",
  "Feels.jpg",
  "Fierce.png",
  "Glass_breaks.jpg",
  "Happy Core 1.png",
  "Happy Core 2.png",
  "Jazz - Meme Jazz.png",
  "Jazz - PostAvant.jpg",
  "Metal - Feels.jpg",
  "Metal - Hipster Metal.jpeg",
  "Mu-core2012.jpg",
  "Mucorecrabcore.jpg",
  "Mucoreinbetweeners.jpg",
  "Mucoremusicians.png",
  "Mucoresoundtrack.jpg",
  "Mucoreswag.jpg",
  "Mucorewhitepeoplemusic.png",
  "Mulittv.jpg",
  "New to mu.jpg",
  "Overarching Story-Core.jpg",
  "Patrician_Rock.jpeg",
  "PATRISHIANCOREMAN.jpg",
  "Scarufficore.png",
  "Shitcore.png",
  "Singing Core.jpg",
  "Sub_mu_Essentials.jpg",
  "Swnss.png",
  "Wrong_generashun.jpeg"
],
"Seasons" : [
  "Christmas.jpg",
  "Halloween.jpg",
  "Outumn Core.png",
  "Summer Core 1.jpg",
  "Summer Core 2.jpg",
  "Summer Core 3.png",
  "Winter Core 1.jpg",
  "Winter Core 2.png"
],
"Themed" : [
  "4AD Record Label.jpeg",
  "Anime Core.jpg",
  "Bald Core.jpg",
  "Color Core.jpg",
  "Creepy & Unsettling 1.jpg",
  "Creepy & Unsettling 2.jpg",
  "Insane Core 1.png",
  "Insane Core 2.png",
  "Kitten Core.jpg",
  "Live Albums.jpg",
  "Loli Core.jpg",
  "September Eleventh.jpg",
  "SexCore.jpg",
  "Video Games.jpg"
],
"Years" : [
  "1400s - 1600s.png",
  "1750s - 1830s.png",
  "1950s Rock'n'Roll.jpg",
  "1950s.png",
  "1960s Jazz 1.jpg",
  "1960s Jazz 2.jpg",
  "1960s Psychedelia.jpg",
  "1960s.jpg",
  "1970s 1.jpg",
  "1970s 2.jpg",
  "1970s 3.jpg",
  "1970s Post-Punk.jpg",
  "1970s Punk.jpg",
  "1980s.jpg",
  "1990s 1.jpg",
  "1990s 2.jpg",
  "1990s Alternative & Grunge.jpg",
  "1990s Electronic.jpg",
  "1990s Punk.jpg",
  "2000s 1.jpg",
  "2000s 2.jpg",
  "2000s Punk.jpg",
  "2010s 1.jpg",
  "2010s 2.jpg",
  "2010s Hip Hop 1.png",
  "2010s Hip Hop 2.jpg",
  "500s - 1400s.png"
]};