const ListsCreated = {"Bands, Artists and Labels" : [
  "311.png",
  "4AD.jpeg",
  "WU-TANG.jpg"
],
"Countries" : [
  "Argentina Math Rock.jpg",
  "Argentina.jpg",
  "Australia.png",
  "Austria.jpg",
  "Belgium.png",
  "Brazil - AvantGarde.jpg",
  "Brazil - Caipira.jpg",
  "Brazil - Pyschedelia.png",
  "Brazil - Rock.png",
  "Brazil - Soul.png",
  "Brazil 1.jpg",
  "Brazil 2.jpg",
  "Brazil 60s.png",
  "Brazil 70s.png",
  "Brazil 80s.png",
  "Canada.jpg",
  "Chile.jpg",
  "France.jpg",
  "Iceland.jpg",
  "Japan 1.png",
  "Japan 2.png",
  "Japan 3.jpg",
  "Japan 4.png",
  "Japan 80s.jpg",
  "Japan Folk.jpg",
  "Mexico.jpg",
  "Northern Ireland.png",
  "Peru.jpg",
  "Poland Synthpop.jpg",
  "Poland.jpg",
  "Portugal.jpg",
  "Quebec -Black Metal.jpg",
  "Scotland.png",
  "Spain - Black Metal.jpg",
  "Spain - Death Metal.png",
  "Spain - Doom Metal.png",
  "Spain - Early Metal.png",
  "Spain - Metal.jpg",
  "Spain - Modern Heavy Metal.png",
  "Spain - Power Metal.png",
  "Spain - Rap.png",
  "Spain - Thrash Metal.png",
  "Sweden - Death Metal.jpg",
  "UK Hiphop.jpg",
  "United States - Americana.jpg",
  "United States -Black Metal.jpg"
],
"Drugs" : [
  "Lsd Core.png",
  "Weed Core 1.jpeg",
  "Weed Core 2.jpeg"
],
"Genres" : [
  "Ambient - Atmospheric.jpg",
  "Ambient - Dark Ambient 1.jpg",
  "Ambient - Dark Ambient 2.png",
  "Ambient 1.jpeg",
  "Ambient 2.png",
  "Ambient 3.jpg",
  "Bossa 1.jpg",
  "Bossa 2.jpg",
  "Classical - Ancient .png",
  "Classical - Contemporary Classical.jpg",
  "Classical 1.png",
  "Classical 2.jpg",
  "Classical 3.png",
  "Classical 4.jpg",
  "Funk - Modern.jpg",
  "Funk 1.jpg",
  "Future Funk 1.png",
  "Future Funk 2.jpg",
  "Future Funk 3.png",
  "Hip Hop - Bay Area.jpg",
  "Hip Hop - Concept.jpg",
  "Hip Hop - East Coast.jpg",
  "Hip Hop - Experimental 1.png",
  "Hip Hop - Experimental 2.jpg",
  "Hip Hop - Experimental 3.jpg",
  "Hip Hop - Instrumental.png",
  "Hip Hop - Noise.jpg",
  "Hip Hop - Southern.jpg",
  "Hip Hop - Triphop.jpeg",
  "HIp Hop - West Coast.jpg",
  "Hip Hop 1.jpg",
  "Hip Hop 2.jpg",
  "Hip Hop 3.jpg",
  "Hip Hop 4.jpg",
  "Jazz - Acid Funk.jpeg",
  "Jazz - Meme Jazz.png",
  "Jazz - Post Avan Guard.jpg",
  "Jazz - PostAvant.jpg",
  "Jazz 1.jpg",
  "Jazz 2.jpg",
  "Jazz 3.jpg",
  "Jazz 4.jpg",
  "Jazz 5.jpg",
  "Jazz Chamber.jpeg",
  "Jazz Guitar.png",
  "Metal - Atmospheric Black Metal.png",
  "Metal - Atmospheric Sludge.png",
  "Metal - Avant Garde.jpg",
  "Metal - Black & Trash Metal.jpg",
  "Metal - Black Metal 1.jpg",
  "Metal - Black Metal 2.jpg",
  "Metal - Black Metal 3.jpg",
  "Metal - Black Metal 4 Ultimate.png",
  "Metal - But Metal.jpg",
  "Metal - Death Metal 1.jpg",
  "Metal - Death Metal 2.png",
  "Metal - Death Metal 3.jpg",
  "Metal - Djent.jpg",
  "Metal - Doom Metal.jpg",
  "Metal - Feels.jpg",
  "Metal - Folk Metal 1.jpg",
  "Metal - Folk Metal 2.png",
  "Metal - Hipster Black Metal.png",
  "Metal - Hipster Metal.jpeg",
  "Metal - Industrial Metal.png",
  "Metal - Instrumental Metal.png",
  "Metal - Melodic Death Metal.jpg",
  "Metal - Nu Metal.jpg",
  "Metal - PostHardcore.jpg",
  "Metal - Power Metal 1.jpg",
  "Metal - Power Metal 2.jpg",
  "Metal - Power Metal 3.jpg",
  "Metal - Progressive Metal.jpg",
  "Metal - Space Black Metal.jpg",
  "Metal - Subgenre Chart 1.jpg",
  "Metal - Subgenre Chart 2.jpg",
  "Metal - Subgenre Chart 3.jpg",
  "Metal - Thrash Metal.jpg",
  "Metal - Top100 .jpg",
  "Metal - Traditional Metal.png",
  "Reggae - Reggaeton.jpg",
  "Reggae 1.jpg",
  "Reggae 2.png",
  "Reggae 3.png",
  "Vapor Wave 1.jpg",
  "Vapor Wave 2.jpg",
  "Vapor Wave 3.png",
  "Vapor Wave 4.jpg",
  "Vapor Wave 5.jpg",
  "Vapor Wave 6.jpg",
  "Vapor Wave 7.jpg"
],
"Internet" : [
  "4chan Board Core 1.png",
  "4chan Board Core 2.jpg",
  "4chan LeftyPol.jpg",
  "4chan Mu - Musicians.png",
  "4chan Mu - New to mu.jpg",
  "4chan Mu - Sub Essentials.jpg",
  "4chan Mu.jpg",
  "4chan Pol.jpg",
  "4chan X 1.png",
  "4chan X 2.jpg",
  "9gag Core.jpg",
  "Fantano Core.png",
  "Fedora Core.jpg",
  "Tumblr.png",
  "Twitter Core 1.png",
  "Twitter Core 2.jpg"
],
"Mental States" : [
  "Boring Core.jpg",
  "Breakbeat.jpg",
  "Feels 1.jpg",
  "Fierce.png",
  "Happy Core 1.png",
  "Happy Core 2.png",
  "Insane Core 1.png",
  "Insane Core 2.png",
  "Singing Core.jpg",
  "Suicide Chart.jpg"
],
"Seasons" : [
  "Autumn 1.jpg",
  "Autumn 2.png",
  "Christmas.jpg",
  "Halloween.jpg",
  "Summer Core 1.jpg",
  "Summer Core 2.jpg",
  "Summer Core 3.png",
  "Winter Core 1.jpg",
  "Winter Core 2.png"
],
"Soundtracks" : [
  "Anime.jpg",
  "Film Scores.jpg",
  "Video Games.jpg"
],
"Themed" : [
  "Bald Core.jpg",
  "Bass & Drums.png",
  "Brave New World.jpg",
  "Color Core.jpg",
  "Concept Albums.png",
  "Crab Core.jpg",
  "Creepy & Unsettling 1.jpg",
  "Creepy & Unsettling 2.jpg",
  "DadRockers Guide to Modern Music.jpg",
  "Field Recordings.png",
  "Flame Shirt Core.png",
  "Glass Breaks.jpg",
  "Kitten Core.jpg",
  "Live Albums.jpg",
  "Loli Core.jpg",
  "Millennial Scaruffi Core.png",
  "Overarching Story Core.jpg",
  "Patrician Core.jpg",
  "September Eleventh.jpg",
  "SexCore.jpg",
  "Shitcore.png",
  "Swag Core.jpg",
  "White People Music.png",
  "Wrong Generashun.jpeg"
],
"Years" : [
  "1400s - 1600s.png",
  "1750s - 1830s.png",
  "1950s Rock'n'Roll.jpg",
  "1950s.png",
  "1960s Jazz 1.jpg",
  "1960s Jazz 2.jpg",
  "1960s Psychedelia.jpg",
  "1960s.jpg",
  "1970s 1.jpg",
  "1970s 2.jpg",
  "1970s 3.jpg",
  "1970s Post-Punk.jpg",
  "1970s Punk.jpg",
  "1980s Punk.jpg",
  "1980s.jpg",
  "1990s 1.jpg",
  "1990s 2.jpg",
  "1990s Alternative & Grunge.jpg",
  "1990s Electronic.jpg",
  "1990s Punk.jpg",
  "2000s 1.jpg",
  "2000s 2.jpg",
  "2000s Ambient.jpg",
  "2000s Indie Rock.jpg",
  "2000s Punk.jpg",
  "2010s 1.jpg",
  "2010s 2.jpg",
  "2010s Hip Hop 1.png",
  "2010s Hip Hop 2.jpg",
  "500s - 1400s.png"
]};